version: '3'

services:

  mysql:
    image: mysql:5
    volumes:
    - ./bin/local-dev/mysql:/var/lib/mysql
    - ./bin/local-dev/wordpress/config/mysql/wptests.sql:/docker-entrypoint-initdb.d/wptests.sql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    build:
      context: ./bin/local-dev/wordpress
      args:
        WP_VERSION: ${WP_VERSION}
    depends_on:
      - mysql
    ports:
      - ${WP_HTTP_PORT}:80
    volumes:
      - ./bin/local-dev/wordpress/html:/var/www/html
      - .:/var/www/html/wp-content/plugins/foo-bar
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_HTTP_PORT: ${WP_HTTP_PORT}

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
